# Generated by Django 6.0.2 on 2026-02-24 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_name", models.CharField(max_length=30)),
                ("account_number", models.CharField(max_length=30)),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tx_type", models.CharField(choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")], max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("transaction_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "현금"), ("CARD", "카드"), ("TRANSFER", "계좌이체")], max_length=20
                    ),
                ),
                ("counterparty", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="accounts.account"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(fields=("user", "account_number"), name="uniq_user_account_number"),
        ),
    ]
