# Generated by Django 6.0.2 on 2026-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_transaction_tx_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="tx_type",
            field=models.CharField(choices=[("INCOME", "수입"), ("EXPENSE", "지출")], max_length=20),
        ),
    ]
